FROM golang:alpine AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/ cmd/
COPY config/ config/
COPY internal/ internal/
COPY pkg/ pkg/

RUN CGO_ENABLED=0 GOOS=linux go build -o /switchboard cmd/switchboard/switchboard.go

FROM scratch

WORKDIR /

ENV USER=msn
ENV GROUP=msn

COPY --from=build-stage /switchboard /switchboard

USER 65532:65532

EXPOSE 1863

ENTRYPOINT ["/switchboard"]